version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    cooldown:
      default-days: 14
    schedule:
      interval: "daily"
    commit-message:
      prefix: build
      include: scope
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    cooldown:
      default-days: 14
    commit-message:
      prefix: ci
      include: scope

